In [13]:
!pip install -r ../requirements.txt

Requirement already satisfied: numpy in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 1)) (2.3.2)
Requirement already satisfied: pandas in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: scikit-learn in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: openai in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 4)) (1.99.7)
Requirement already satisfied: groq in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 5)) (0.31.0)
Requirement already satisfied: seaborn in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 6)) (0.13.2)
Requirement already satisfied: dotenv in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 7)) (0.9.9)
Requirement already satisfied: matplotlib in d:\installation\anaconda\envs\myenv\lib\site-packages (from -r ../requirements.txt (line 8)) (3.10.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\installation\anaconda\envs\myenv\lib\site-packages (from pandas->-r ../requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\installation\anaconda\envs\myenv\lib\site-packages (from pandas->-r ../requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\installation\anaconda\envs\myenv\lib\site-packages (from pandas->-r ../requirements.txt (line 2)) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from scikit-learn->-r ../requirements.txt (line 3)) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from scikit-learn->-r ../requirements.txt (line 3)) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from scikit-learn->-r ../requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (2.11.7)
Requirement already satisfied: sniffio in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: tqdm>4 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in d:\installation\anaconda\envs\myenv\lib\site-packages (from openai->-r ../requirements.txt (line 4)) (4.14.1)
Requirement already satisfied: idna>=2.8 in d:\installation\anaconda\envs\myenv\lib\site-packages (from anyio<5,>=3.5.0->openai->-r ../requirements.txt (line 4)) (3.10)
Requirement already satisfied: certifi in d:\installation\anaconda\envs\myenv\lib\site-packages (from httpx<1,>=0.23.0->openai->-r ../requirements.txt (line 4)) (2025.8.3)
Requirement already satisfied: httpcore==1.* in d:\installation\anaconda\envs\myenv\lib\site-packages (from httpx<1,>=0.23.0->openai->-r ../requirements.txt (line 4)) (1.0.9)
Requirement already satisfied: h11>=0.16 in d:\installation\anaconda\envs\myenv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->-r ../requirements.txt (line 4)) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from pydantic<3,>=1.9.0->openai->-r ../requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in d:\installation\anaconda\envs\myenv\lib\site-packages (from pydantic<3,>=1.9.0->openai->-r ../requirements.txt (line 4)) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from pydantic<3,>=1.9.0->openai->-r ../requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: python-dotenv in d:\installation\anaconda\envs\myenv\lib\site-packages (from dotenv->-r ../requirements.txt (line 7)) (1.1.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (25.0)
Requirement already satisfied: pillow>=8 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\installation\anaconda\envs\myenv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (3.2.3)
Requirement already satisfied: six>=1.5 in d:\installation\anaconda\envs\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r ../requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: colorama in d:\installation\anaconda\envs\myenv\lib\site-packages (from tqdm>4->openai->-r ../requirements.txt (line 4)) (0.4.6)

In [16]:
import numpy as np
import pandas as pd
import os #if im not know about my current library
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

Normalization Vs Standerization

    Normalization is a texhnique in which values are shifted and rescaled and so endded up ranging between 0 and 1.also known as min-max scalling

    Standerization is a technique wheree the values are centered arround the mean with an unit standard deviation.this means that the mean of the attribute becomes zero and the resultant distribution has a unit standard deviation

In [15]:
df = pd.read_csv('./data/processed/ChurnModeling_feature_encoding.csv')
df.head()

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,42.00,2,0.00,1,1,1,101348.88,1,1,True,False,False,True,False
1,41.00,1,83807.86,1,0,1,112542.58,0,1,False,False,True,True,False
2,42.00,8,159660.80,3,1,0,113931.57,1,0,True,False,False,True,False
3,38.91,1,0.00,2,0,0,93826.63,0,2,True,False,False,True,False
4,43.00,2,125510.82,1,1,1,79084.10,0,3,False,False,True,True,False


    [
    "| Condition | Min-Max Scaling | Standardization (Z-score) |\n",
    "|-----------|----------------|------------------------|\n",
    "| Data has a known, fixed range | ✅ Yes | ❌ Not ideal |\n",
    "| Data contains outliers | ❌ Sensitive to outliers | ✅ More robust to outliers |\n",
    "| Data is normally distributed | ❌ Not necessary | ✅ Preferred |\n",
    "| Data is not normally distributed (e.g., skewed) | ✅ If shape needs to be preserved | ✅ Often works well after log-transform |\n",
    "| Model is distance-based (KNN, SVM) | ✅ Recommended | ✅ Also acceptable |\n",
    "| Model is neural network | ✅ Strongly recommended | ❌ May slow training |\n",
    "| Model is linear or uses regularization | ❌ Not ideal | ✅ Helps with convergence |\n",
    "| Input features need bounded values (0–1) | ✅ Required | ❌ Not bounded |\n",
    "| Applying PCA or LDA | ❌ May distort variance | ✅ Required (centering needed) |\n",
    "| Want to preserve original distribution shape | ✅ Maintains feature shape | ✅ Maintains shape but centers data |\n",
    "| Working with tree-based models | ❌ Not needed | ❌ Not needed |"
   ]

In [17]:
columns_needtobe_scaled=['Age','Tenure','Balance','EstimatedSalary']
for col in columns_needtobe_scaled:
    standard_scalar = StandardScaler()
    df[col] = standard_scalar.fit_transform(df[col].values.reshape(10000,1))

In [18]:
df

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,0.302983,-1.041760,-1.225848,1,1,1,0.021886,1,1,True,False,False,True,False
1,0.204867,-1.387538,0.117350,1,0,1,0.216534,0,1,False,False,True,True,False
2,0.302983,1.032908,1.333053,3,1,0,0.240687,1,0,True,False,False,True,False
3,-0.000196,-1.387538,-1.225848,2,0,0,-0.108918,0,2,True,False,False,True,False
4,0.401100,-1.041760,0.785728,1,1,1,-0.365276,0,3,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.008634,-0.004426,-1.225848,2,1,0,-0.066419,0,4,True,False,False,False,True
9996,-0.383831,1.724464,-0.306379,1,1,1,0.027988,0,0,True,False,False,False,True
9997,-0.285715,0.687130,-1.225848,1,0,1,-1.008643,1,2,True,False,False,True,False
9998,0.302983,-0.695982,-0.022608,2,1,0,-0.125231,1,4,False,True,False,False,True
9999,-1.070646,-0.350204,0.859965,1,1,0,-1.076370,0,4,True,False,False,True,False

In [19]:
df.to_csv('./data/processed/ChurnModeling_Final.csv',index=False)